#180884980 Create Top Navigation using existing components
Amcovad/amcovad-frontend pull request #10
Opened 2022-01-12 12:58 UTC by RACHID-WEBDEV

#### What does this PR do?
 - Create a Top Navigation using existing components
#### Description of Task to be completed?
- Create Navbar components
- Add a Logo SVG image
- import the button component
#### How should this be manually tested?
- Clone the repo
- Run `npm install` or `yarn install` in your terminal to install the required dependencies.
- Run `npm run dev` or  `yarn dev` to start 
- Open your browser and visit `http://localhost:3000/`

2022-01-12 17:45 UTC, andela-hpopoola requested changes
Thank you for working on this. 

I noticed a couple on this on best practices:
1. The branch name `ft-Create-Top-Navigation-using-existing-components-#180884980` can be improved to meet practises as follows: 
- your branch names should always be in lower case and not mixed case 
- The hash symbol before the Pivotal Tracker Id is not necessary
- - 2 or 3 can be used in this instance for the branch name (highest 5)

Something like `ft-create-top-navigation-180884980` should suffix for the branch name. Please note that no action is required from you on this, I am just pointing it out to ensure that you follow the conventions we agreed on here
 
https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices

2. It might also be better to include a screenshot the Navbar you have created in the PR description

3. Since the Storybook story has been approved, I think it is better to integrate this into Storybook too. You can read this Git workflow for more information on rebasing:

https://github.com/andela/bestpractices/wiki/Git-Workflow

Thank you for the hard work 💯 .

2022-01-12 17:45 UTC, andela-hpopoola commented on components/Navbar.js
> +          <Button>try it now</Button>
This should be written in the right case.

```suggestion
          <Button>Try it now</Button>
```

2022-01-12 17:45 UTC, andela-hpopoola commented on pages/index.js
> +      <br />
We should use a padding or margin bottom here instead of `<br />`

2022-01-15 07:18 UTC, andela-hpopoola commented
Thank you for your hard work on this. A gentle reminder that you have awaiting comments on this PR. Feel free to work on it when you are chanced, I only wanted to be sure that I am not the one delaying your work on this. Thank you.

2022-01-16 13:36 UTC, andela-hpopoola commented
Thank you for helping out with this. I have updated the branch here to be in sync with the current `main` branch to make it easier to work it for you. Thank you.

2022-01-16 17:14 UTC, RACHID-WEBDEV commented
### Top Navigation component
![header](https://user-images.githubusercontent.com/71451975/149670264-2f816dd1-0ac6-4f40-b151-c973822f803f.png)

2022-01-16 17:18 UTC, andela-hpopoola commented
> ### Top Navigation component
> ![header](https://user-images.githubusercontent.com/71451975/149670264-2f816dd1-0ac6-4f40-b151-c973822f803f.png)


Awesome. Thank you for adding this but I think this should be added to the PR (I have added it above) 🙌🏽

2022-01-17 05:24 UTC, andela-hpopoola approved these changes
Thank you for the hard work on this. I believe it is safe to merge this now.

2022-01-18 00:01 UTC, merged