#182507028 Ft Modified Form Components Design
Amcovad/amcovad-frontend pull request #43
Opened 2022-06-29 10:02 UTC by RACHID-WEBDEV

#### What does this PR do?
Modified Form Components Design System
#### Description of Task to be completed?
- Modified the  `Input Component`  
- Modified the  `Select component` 
- Modified the  `Radio Button Component` 
- Modified the  `Toggle Button Component` 
- Modified the  `Checkbox Button Component` 
- Modified the  `Labels Component` 

#### How should this be manually tested?
- Clone the Repository
- Run `yarn Install` in your terminal to install required dependencies
-  Run `yarn dev` to start the local development server on `localhost:3000//form-component`
below attached the image preview

![form-component-2022-06-29-10_58_53](https://user-images.githubusercontent.com/71451975/176409608-ecd8fdb8-693d-4811-8024-a19b98997c6a.png)

2022-06-30 07:02 UTC, andela-hpopoola requested changes
Thank you for helping out with this. I dropped a few comments but I think we can look more into it when and if we sync.

Thank you for the hard work.

2022-06-30 07:02 UTC, andela-hpopoola commented on components/form/Textarea.js
> +  withHintText
No sure why you added `with` to the variable names. I believe we could use a better name based on the usecase.

2022-07-02 12:29 UTC, RACHID-WEBDEV commented on components/form/Form.js
> +  defaultValues = { email: '', password: '', confirmPassword: '', acceptTerms: false }
noted it will remove

2022-08-11 09:10 UTC, andela-hpopoola approved these changes

2022-08-11 10:24 UTC, merged